name: Deploy Frontend Application

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy_frontend:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Copy updated frontend files
        run: |
          rsync -av --delete /home/projects/frontend/ /var/www/html/
          sudo chown -R www-data:www-data /var/www/html
